replicaCount: 1

app:
  image:
    repository: caddy
    tag: latest
    pullPolicy: Never
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  reverse_proxy_hostname: "app.qualifire.local"
  target_hostname: "app.qualifire.ai"
  storage:
    size: 5Gi
    storageClassName: "standard"

proxy:
  image:
    repository: caddy
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  reverse_proxy_hostname: "proxy.qualifire.local"
  target_hostname: "proxy.qualifire.ai"
  storage:
    size: 5Gi
    storageClassName: "standard"

ingress:
  enabled: true
  className: "nginx"

service:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
