apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-qualifire-app-rp
  labels:
    app: {{ .Release.Name }}-qualifire-app-rp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-qualifire-app-rp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-qualifire-app-rp
    spec:
      containers:
        - name: qualifire-app-rp
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          resources: {{ toYaml .Values.app.resources | nindent 12 }}
          env:
            - name: REVERSE_PROXY_HOSTNAME
              value: "{{ .Values.app.reverse_proxy_hostname }}"
            - name: TARGET_HOSTNAME
              value: "{{ .Values.app.target_hostname }}"
          command: ["/bin/sh"]
          args:
            - -c
            - |
              apk add nss-tools curl &&
              curl --output /etc/caddy/Caddyfile https://pastebin.com/raw/R5rUikQU &&
              caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
          volumeMounts:
            - name: app-data-volume
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -k --resolve $REVERSE_PROXY_HOSTNAME:443:127.0.0.1 https://$REVERSE_PROXY_HOSTNAME
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: app-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-qualifire-app-rp-data
