apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-rp-service
spec:
  selector:
    app: {{ .Release.Name }}-app-rp
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
