apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualifire-app-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualifire-app-caddy
  template:
    metadata:
      labels:
        app: qualifire-app-caddy
    spec:
      containers:
        - name: qualifire-app-caddy-container
          image: mycaddy:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: CADDY_HOSTNAME
              value: "app.qualifire.local"  # this should definetly be an item in values
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            # k8s doesn't support SNI certificates, so we can't use httpGet probe
            exec:
              command: 
                - sh  # using sh to be able to use env vars
                - -c
                - curl -k --resolve $CADDY_HOSTNAME:443:127.0.0.1 https://$CADDY_HOSTNAME
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
