apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qualifire-proxy-rp-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.proxy.storage.size }}
  storageClassName: {{ .Values.proxy.storage.storageClassName }}
