name: Helm Chart Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint and Template Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Run Helm Lint
        run: |
          helm lint .
      
      - name: Verify Helm Templates
        run: |
          helm template mychart . --debug
      
      - name: Run Helm Dry-Run Install
        run: |
          helm install test-release . --dry-run --debug
  